---
- name: Install Dependencies Packages
  ansible.builtin.package:
    name: "{{ dependencies_packages }}"
    state: present
    update_cache: yes

- name: Install Python Packages
  ansible.builtin.package:
    name: "{{ python_packages }}"
    state: present
    update_cache: yes