python_packages:
  - python3-dev
  - python3-pip
  - python3-setuptools

dependencies_packages:
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - curl
  - gnupg-agent
  - gnupg2
  - molly-guard
  - pass
