apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-time1
spec:
  generators:
  - git:
      repoURL: https://github.com/leoviana00/lab-kustomize-app-demo.git
      revision: HEAD
      directories:
      - path: demo-app-argo/bootstrap/overlays/default/
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: time1
      source:
        repoURL: https://github.com/leoviana00/lab-kustomize-app-demo.git
        targetRevision: HEAD
        path: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: time1
