---
- name: Install Istio
  shell: |
    curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.16.2 TARGET_ARCH=x86_64 sh -
    cd istio-1.16.2
    export PATH=$PWD/bin:$PATH
    istioctl install --set profile=default -y
    kubectl label namespace default istio-injection=enabled
  register: Istio_install

- name: Display Istio install (Output)
  debug:
    var: Istio_install.stdout_lines

- name: Get a list of all namespace istio-system
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: istio-system
  register: pod_list

- name: Display pods Istio-system (Output)
  debug:
    var: pod_list | json_query('resources[].[metadata.name, metadata.namespace]')

# - name: Install Grafana
#   shell: |
#     kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.16/samples/addons/grafana.yaml
#   register: grafana_install

# - name: Install kiali
#   shell: |
#     kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.16/samples/addons/kiali.yaml
#   register: kiali_install

# - name: Install Prometheus
#   shell: |
#     kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.16/samples/addons/prometheus.yaml
#   register: prometheus_install