apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-go-01
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: squad-a
  source:
    repoURL: >-
      https://github.com/leoviana00/lab-devops-cloud-eks.git
    path: gitops/apps/squad-a/webserver-go-01/overlays/staging
    targetRevision: dev
    kustomize:
      commonAnnotations:
        app/kustomize: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: webserver-hom