---

- name: Requirements Install
  gather_facts: false
  hosts: k8s-lab-master-1
  remote_user: vagrant
  become: true
  tags: requirements
  roles:
    - role: requirements_configure

- name: Update Kubeconfig
  gather_facts: false
  hosts: k8s-lab-master-1
  remote_user: vagrant
  become: true
  tags: kubeconfig
  roles:
    - role: kubeconfig_configure

- name: Install Helm
  gather_facts: false
  hosts: k8s-lab-master-1
  remote_user: vagrant
  become: true
  tags: helm
  roles:
    - role: helm_configure

- name: Install Istio
  gather_facts: false
  hosts: k8s-lab-master-1
  remote_user: vagrant
  become: true
  tags: istio
  roles:
    - role: istio_configure

- name: Install Argo CD
  gather_facts: false
  hosts: k8s-lab-master-1
  remote_user: vagrant
  become: true
  tags: argo
  roles:
    - role: argocd_configure

- name: Install Haproxy Ingress Controller
  hosts: k8s-lab-master-1
  remote_user: vagrant
  become: true
  tags: haproxy
  roles:
    - role: haproxy_configure

- name: Installing ALB Controller
  gather_facts: false
  hosts: localhost
  tags: alb
  roles:
    - role: alb_configure