apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-istio-default
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: features
  source:
   repoURL: "https://istio-release.storage.googleapis.com/charts"
   chart: "default"
   targetRevision: 1.22.1
   helm:
     releaseName: istio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
